# Generated by Django 4.0.2 on 2022-04-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(max_length=700)),
                ('detalhe', models.TextField()),
                ('link_github', models.URLField()),
                ('link_demo', models.URLField()),
                ('img_portfolio', models.ImageField(blank=True, default='', upload_to='portapp/img/')),
                ('img_prev', models.ImageField(blank=True, default='', upload_to='portapp/img/')),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portapp.categoria')),
            ],
        ),
    ]
