# Generated by Django 4.0.2 on 2022-04-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliodetails',
            old_name='categoria',
            new_name='categoria_nome',
        ),
        migrations.RemoveField(
            model_name='portfoliodetails',
            name='img_portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliodetails',
            name='img_prev',
        ),
    ]
