# Generated by Django 4.0.2 on 2022-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_rename_categoria_portfoliodetails_categoria_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioDetails',
            new_name='PortfolioDetail',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria_nome',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
