# Generated by Django 4.0.2 on 2022-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_rename_portfoliodetails_portfoliodetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetail',
            name='link_demo',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='link_github',
            field=models.URLField(blank=True, default=None),
        ),
    ]
