# Generated by Django 4.0.2 on 2022-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_alter_portfoliodetail_link_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetail',
            name='img_portfolio',
            field=models.ImageField(blank=True, default='', upload_to='portapp/img/'),
        ),
        migrations.AddField(
            model_name='portfoliodetail',
            name='img_prev',
            field=models.ImageField(blank=True, default='', upload_to='portapp/img/'),
        ),
    ]
