# Generated by Django 4.0.2 on 2022-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_alter_portfoliodetail_img_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetail',
            name='img_portfolio',
            field=models.ImageField(blank=True, default='portapp/img/img-placeholder.webp', upload_to='portapp/img/'),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='img_prev',
            field=models.ImageField(blank=True, default='portapp/img/img-placeholder.webp', upload_to='portapp/img/'),
        ),
    ]
