# Generated by Django 4.0.2 on 2022-05-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_portfoliodetail_link_como_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testemunha_nome', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('testemunho', models.TextField(max_length=700)),
                ('img_prev', models.ImageField(blank=True, default='portapp/img/img-placeholder.jpg', upload_to='portapp/img/')),
            ],
        ),
    ]
