# Generated by Django 4.0.2 on 2022-05-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0010_testemunhos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testemunhos',
            old_name='testemunha_nome',
            new_name='testemunho_nome',
        ),
        migrations.AlterField(
            model_name='testemunhos',
            name='titulo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
